/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Counter from "~/components/Counter/Counter";

function DoctorCounter() {
  return (
    <Counter className="max-w-[314px]">
      <div className="flex z-10 gap-5 justify-between items-start self-center -mt-3 w-full whitespace-nowrap max-w-[280px]">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/face761ce6bb8f8b03c9c369dff4fbeb8a3b31c30ddcd101363fc8ae5aa33515?placeholderIfAbsent=true&apiKey=38d956dfb74d41e68ea15b3be9162920"
          alt="Illustration related to doctors"
          className="object-contain shrink-0 self-end mt-6 max-w-full aspect-[1.56] w-[115px]"
        />
        <div className="flex flex-col self-start">
          <div className="text-5xl font-black leading-none text-green-700">
            +1200
          </div>
          <h2 className="mt-5 text-4xl font-bold leading-loose text-black text-opacity-90">
            Doctors
          </h2>
        </div>
      </div>
      <p className="mt-4 w-full text-lg leading-7 text-center text-black text-opacity-90">
        Maecenas nisl libero, tincidunt id odio id, feugiat vulputate quam.
      </p>
    </Counter>
  );
}

export default DoctorCounter;
